### PR TITLE
Parse GA4 Client Id

### PR DESCRIPTION
**Pull request by amittiwari1979**
* Created seed, macros and integration test.
* This is now good to be reviewed. Fixed the test as well.

### CODE REVIEW

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
@amittiwari1979 Currently if you pass an invalid extract_value you get an unhelpful "Expected end of input but got keyword AS at [16:6]" message.  

I created a more helpful message and pushed a commit that purposefully fails so you can see an example of an error message... we need to remove the failure before merging this.

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
This macro gets the following error in Snowflake:

16:29:19  Database Error in model test_extract_ga4_client_id (models/test_extract_ga4_client_id.sql)
16:29:19    002140 (42601): SQL compilation error:
16:29:19    Unknown functions OFFSET, OFFSET
16:29:19    compiled Code at target/run/census_utils_integration_tests/models/test_extract_ga4_client_id.sql

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
> This macro gets the following error in Snowflake:
> 
> 16:29:19 Database Error in model test_extract_ga4_client_id (models/test_extract_ga4_client_id.sql) 16:29:19 002140 (42601): SQL compilation error: 16:29:19 Unknown functions OFFSET, OFFSET 16:29:19 compiled Code at target/run/census_utils_integration_tests/models/test_extract_ga4_client_id.sql

@Stephen986 I have fixed the errors for snowflake. The integration test is now working fine for snowflake as well. Now, I will start working on redshift.

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
> > This macro gets the following error in Snowflake:
> > 16:29:19 Database Error in model test_extract_ga4_client_id (models/test_extract_ga4_client_id.sql) 16:29:19 002140 (42601): SQL compilation error: 16:29:19 Unknown functions OFFSET, OFFSET 16:29:19 compiled Code at target/run/census_utils_integration_tests/models/test_extract_ga4_client_id.sql
> 
> @Stephen986 I have fixed the errors for snowflake. The integration test is now working fine for snowflake as well. Now, I will start working on redshift.

@Stephen986 I have fixed all the issues and the code for the macros in this branch is now compatible with redshift, snowflake & bigquery.

**Comment by 7mOatpfIPk6fXjlHH925mn3KecVmtlxoNDCVUpP** [comment]
@amittiwari1979 in the case of the Parse GA 4 macro, the Redshift and Snowflake versions are identical, right?  Should we make the RS/SF version the default and only do a different version for BigQuery so that the number of lines is reduced?

**Comment by 8WlHSebsMM4Z71kjkvD2CAWSP7qyoVEA4ow6GLw** [comment]
> @amittiwari1979 in the case of the Parse GA 4 macro, the Redshift and Snowflake versions are identical, right? Should we make the RS/SF version the default and only do a different version for BigQuery so that the number of lines is reduced?

@Stephen986 This is done. I see another opportunity for the same in country code macro, but snowflake gets the column names in upper case. It can get in lower case if we wrap column alias with a double quote, but BQ takes double quote as string literal, so doesn't works for BQ. Will try more to figure out a way for country code macro

**Review by Stephen986 — APPROVED** [review]

**Pull request merged**
